language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "VM6HTqBZ9qanJvdaKDD2L900kv1bMsMQvqRh76cqT3sRxlUCPy/w87W6wiOTWFH4a4Kz7HEuXS4YiHhuly/gE1sgtKAVOLr1L/cEbJ1U6FNFoBq9N/oRpe/xZ43CVROPFGptWLdytuRx4dpr4gNvnowN3bmT5uM1e6qnoafxW4ZE9pkZVdehRMXAcTDsDDq1f2uV269YFO5XftceSK/smZPIVxtrdLJlZG8i98IYFm/q+M2Nl1VRBwutiL27ch2nufdHfLkqOrRJ+ZW799WthjQQpgq+XokikZNQnBcj/tGn8fwFcT1otTwmbEeo/EF2a2tSbKAguvVV48KdecGHcmqzuth479vMHBI6bh5GCtd5ODnvtwYwGk+w62SyDMhL89S69IoIb7TU7tzJHleC0kejnAguXy7i6QhRgGJDV2UKhci+LT3ZjVU9zdqx+ruYriBVuG/ewgvjSSgJzgBEDQo1tScuXLkrXdaDOCV4fuqOy9nJRUxdgxp3MXNyn+z/9U1WXqK9Is9IJRdZ9IzspbFUDu5Yj4oitpkjmfatbEkpTk0EUrLF9J/0KQNglvQZOdojkz1+1lk+vKwXcMIFhrioId7FRAPNZXDJic3kVzLFL1VvZlkhajin46v+30V1gE58r9aOh4giScOvz1OhVKd/Lqxm1vKMNwR4CRGJw3I="
  app:
    master: pokemon-api-dennis 