language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "aXj7nWyMDyK1HO9e56rwM2nR7OcVHeeFe9blMF69uy4lRwtvZmgAcqXByTUu76FCSSizA5dZzQUQ3Cax36ERCWXa0YpasRWWSIVGEvTgnQvbGCjYJQH3HrHrbjG8+g3dWz63X0ngBEc9udLkjyGYU0zjeO2HCnvPU4FDaEIrO+H6Op+pwkg+CBX3A9ZrPojSfnqluBCQoDMoPv6LAhbpxEmI1i7K5KTR+uVPBY8e4C50VyYLLSnypNS+mwWj6WzbtX3ykct4pCNeV8yf+FQ9RBtV5sQoqpv1B4Tyb4x2/WSuie7MFk/hDpCUoqy0mWDdNNH/v0IWBKdNa68YEI2jmwVNpWmPx+e24q/8ZYnb8w6YCg6nBRNtNERwxUDozfR8j5sgGtbm4fQLRRxmg1FMS/Pf5wRqvhljxtbccNDO8cQlvN+VwVqgHNd9Ngw0euNpI/cOlpnSr8Cfcw0dm0mkYohr9d7s6Lw1/VjS9K5xOS76qI3PlegMh4KQeX0+5OPqJ9mccKB0HRNlGmNE1cfGfGlF1xiQLYdQVW5xIKZJIYxR4wUfxaV6d/e7ioZ9Ep7t/xJ0upgEXTRlrNWsPnfujXPmQ5QHHDbX/8V0tRuMZQ3Om/c6y+YFXl4LlU66MC/+qzlimUNAaLF8R88XBycwBx/ph3h0L+vXQD7zbcDVjn0="
  app:
    master: pokemon-api-DennisAL54